### ISSUE TITLE
使用olmaps.addMarker报错，Cannot read property 'features' of undefined

### ISSUE THREAD

**Issue by hotuns** [44021987/olmaps#1]
```initMap() {
			const maps = new Olmaps({
				target: "map",
				center: this.mapcenter,
				zoom: 5
			});
			maps.setMapType("2");
			maps.addMarker({
				latitude: "26.79000000",
				longitude: "114.90890000",
				name: "单杆-1",
				type: "",
				drag: false
			});
		},
```

很简单的一段代码

**Comment by 44021987** [comment]
addMarker方法参数类型为Array，错误类型没有检测，一直没时间优化我找时间重构

**Comment by 44021987** [comment]
> ```
> 			const maps = new Olmaps({
> 				target: "map",
> 				center: this.mapcenter,
> 				zoom: 5
> 			});
> 			maps.setMapType("2");
> 			maps.addMarker({
> 				latitude: "26.79000000",
> 				longitude: "114.90890000",
> 				name: "单杆-1",
> 				type: "",
> 				drag: false
> 			});
> 		},
> ```
> 
> 很简单的一段代码

你把传入的对象放在数组里就可以了，参考文档
