### ISSUE TITLE
map 上的其他操作参考 openlayers 的官方 API

### ISSUE THREAD

**Issue by a17853726916** [44021987/olmaps#3]
想请问您的这个项目的其他操作是不是就是openlayers的是一样 只不过声明的类的方式是用自己的封装类来声明，谢谢您的这个项目 救了我一命

**Comment by 44021987** [comment]
> 想请问您的这个项目的其他操作是不是就是openlayers的是一样 只不过声明的类的方式是用自己的封装类来声明，谢谢您的这个项目 救了我一命

是基于openlayers的二次封装
